### ISSUE TITLE
"Social Network Login Failure" in First Login

### ISSUE THREAD

**Issue by leips** [danielquinn/albatross#2]
Hi

I just deploy it in Docker (Mac) and I have this issue when I try to login. 

Not online in login part, even in "Sign In" where returns Server Error (500)

How is Tweepy try to authenticated?

**Comment by danielquinn** [comment]
If the server is returning a 500 error, please post it here and I can have a look and see what it says.  Outside of that, I would make sure that you've got your `TWITTER_CONSUMER_KEY` and `TWITTER_CONSUMER_SECRET` set in your .env file and that these values come from an app you've created on Twitter's end.

Also note that when you create that app on Twitter's end, you'll need to put this under Settings » Callback URL:

    http://127.0.0.1:8000/accounts/twitter/login/callback/

From the help text Twitter has provided under that box, it appears that the URL in question doesn't really matter, as Albatross sends the return URL along during authentication anyway.  However, leaving this box blank may stop authentication from working at all.

Please let me know if this works for you, and if it does, I'll update the README to be more helpful in this regard.

**Comment by danielquinn** [comment]
I've just updated the README with much more detailed instructions, so I'm closing this.
